### ISSUE TITLE
Extract translations from JSON and Excel metadata files

### ISSUE THREAD

**Issue by arthur-shaw** [lsms-worldbank/susometa#5]
## Background

The questionnaire metadata contains translations in a few ways.

The list of translations, along with their UUID and name, appears in the `Translations` object the end of the JSON file. For example:

```
  "Translations": [
    {
      "Id": "6cb3ee41-0e36-994c-a9a9-2e596323f9da",
      "Name": "Français"
    }
  ],
```

The translations themselves live in `Translations/{translation_uuid}.xlsx`, where the UUID in the file name matches the UUID in the JSON file's translation list.

The translation file contains these columns:

- `Entity Id`, which matches the questionnaire object's `PublicKey` attribute in JSON
- `Variable`, the variable name in the questionnaire
- `Type`, the attribute being translated
- `Index`, the answer option index
- `Original text`, the invariant "original" text in Designer's UI
- `Translation`, the translation

## Tasks

- [ ] Parse `Translations` object in JSON
- [ ] Injest translations from translation file in `Translations/{translation_uuid}.xlsx`
- [ ] Think where to store/how to access them. For example, have `parse_questionnaire` return a list of data frames (e.g., question objects, translations, etc.)
