### ISSUE TITLE
Extract reusable categories from JSON and Excel files

### ISSUE THREAD

**Issue by arthur-shaw** [lsms-worldbank/susometa#6]
## Background

Information about reusable categories exist in a few places in SuSo questionnaire metadata.

The first is a list, in the `Categories` object, found at the end of the JSON file. For example:

```
  "Categories": [
    {
      "Id": "88cc96f5-5b5e-408b-8255-b1ea0acf5819",
      "Name": "yes_no"
    }
  ],
```

The second is a reference to the categories used for a particular question. For example, this question references in the `CategoriesId` the category ID from the example above.

```
        {
          "$type": "SingleQuestion",
          "QuestionType": 0,
          "ShowAsList": false,
          "CategoriesId": "88cc96f5-5b5e-408b-8255-b1ea0acf5819",
          "Answers": [],
          "Children": [],
          "ConditionExpression": "",
          "HideIfDisabled": false,
          "Featured": false,
          "Instructions": "",
          "Properties": {
            "HideInstructions": false,
            "UseFormatting": false
          },
          "PublicKey": "33c704f3-bbb2-7f8c-14e1-64e0d44851ed",
          "QuestionScope": 0,
          "QuestionText": "Do you live in Zimbabwe?",
          "StataExportCaption": "in_zim",
          "VariableLabel": "",
          "IsFilteredCombobox": false,
          "IsTimestamp": false,
          "ValidationConditions": [],
          "VariableName": "in_zim"
        }
```

The third place is in the categories file found in `Categories/{category_uuid}.xlsx`, where `category_uuid` is the category ID referenced above.

This file contains these columns:

- `id`, the answer option index
- `text`, the answer option text
- `parentid`, the ID of the parent in the case of cascading selections
- `attachmentname`

## Tasks

- [x] Extract `Categories` object from JSON
- [x] Extract categories from `Categories/{category_uuid}.xlsx`
- [x] Think about way to store/return categories. For example, have `parse_questionnaire()` return a list of questionnaire metadata data frames (e.g., questionnaire objects, translations, categories, etc.)
